# Generated by Django 3.2.11 on 2022-05-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
