# Generated by Django 3.2.11 on 2022-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_logo',
            field=models.ImageField(blank=True, default='abc.png', null=True, upload_to='profile_pic'),
        ),
    ]
