# Generated by Django 3.2.11 on 2022-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_business_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='select your business url'),
        ),
    ]
