# Generated by Django 3.2.11 on 2023-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230326_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
