# Generated by Django 3.2.11 on 2023-04-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230328_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key_forget_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_password_forget',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
