# Generated by Django 3.2.11 on 2023-01-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_qr', '0002_remove_product_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_description',
        ),
    ]
